### ISSUE TITLE
[OLD] US.02 Instructor Login

### ISSUE THREAD

**Issue by timmooore** [SacciadisG/Group1-SOEN341_Project_F24#7]
As an instructor, I want to log in to the peer assessment system, so that I can create teams for projects and assign students to them.

## Details
- Need to decide how instructors are allocated usernames and passwords.

## Tasks

- #8
## Acceptance Criteria
- [ ] Instructor can log in with a user name and password.
- [ ]

**Comment by NicG27** [comment]
Story board has been updated. Closing old issues
