### ISSUE TITLE
[OLD] Task.01.03 Authenticate user logins

### ISSUE THREAD

**Issue by timmooore** [SacciadisG/Group1-SOEN341_Project_F24#8]
## Description

- All types of new users must register by providing necessary information.
- Passwords should be protected in database for security, probably via hashing and salting.
- Credentials submitted by user through a log in form are validated. Log in is only successful if user provided valid credentials.
- Create a session token for the user upon successful log in.

## Acceptance criteria

- [ ] New users can register by providing valid registration information, such as student IDs.
- [ ] Password pairs are hashed and salted for security.

**Comment by NicG27** [comment]
Story board has been updated. Closing old issues

**Comment by NicG27** [comment]
Story board has been updated. Closing old issues
